my_string = input('Напишите ваше впечатление от курса: ')
number_of_characters = my_string
print('Количество символов в строке:', len(my_string))
print(my_string .upper()+',', 'количество символов в строке:',len(my_string))
print(my_string .lower()+',', 'количество символов в строке:',len(my_string))
print(my_string.replace(' ','')+',', ' количество символов в строке:',end='')
number_of_characters=len(my_string.replace(' ',''))
print(number_of_characters)
print(my_string[0]+',',end='')
#len(my_string[0])
number_of_characters= len(my_string[0])
print('количество символов в строке:',number_of_characters)
print(my_string[-1]+',', 'количество символов в строке:',end='')
number_of_characters= len(my_string[-1])
print(number_of_characters)
# команды len() и end= посмотрел как работают в интернете, хотелось результат красиво смотрелся 
